name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to migrate'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      migration_file:
        description: 'Migration file to run (optional)'
        required: false
        type: string

env:
  NODE_VERSION: '18'

jobs:
  migrate-database:
    name: Run Database Migration
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Supabase CLI
        run: |
          npm install -g supabase
          supabase --version

      - name: Login to Supabase
        run: |
          echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | supabase auth login --token

      - name: Link to Supabase project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Run specific migration
        if: github.event.inputs.migration_file != ''
        run: |
          supabase db push --file supabase/migrations/${{ github.event.inputs.migration_file }}

      - name: Run all pending migrations
        if: github.event.inputs.migration_file == ''
        run: |
          supabase db push

      - name: Verify migration
        run: |
          supabase db diff --schema public

      - name: Notify migration completion
        run: |
          echo "✅ Database migration completed successfully for ${{ github.event.inputs.environment }}"
